name: RedRadar 

on:
  workflow_dispatch: {}
  schedule:
    # 09:30 AM CST (UTC-6) => 15:30 UTC
    - cron: "30 15 * * 1-5"
    # 01:00 PM CST (UTC-6) => 19:00 UTC
    - cron: "0 19 * * 1-5"

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      INDICES: "NDX"                 # or "SPX" or "BOTH"
      THRESHOLD: "-4"
      INTRADAY_1D: "true"            
      PREPOST: "false"
      TIMEFRAMES: "1d,5d,1mo,3mo,6mo,1y,5y"
      LIMIT_TICKERS: "0"
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run RedRadar
        run: python script.py
